### PR TITLE
coderan update datasets

### PR DESCRIPTION
**Pull request by BestAnHongjun**
1.Update the contens - dataset.
2.The organizational structure of `video augmentation methods` has been optimized.
3.Both English version and Chinese version have been updated.

### CODE REVIEW

**Comment by BestAnHongjun** [comment]
1.Update the contents: `dataset`, `training`, `inference`
2.The organizational structure of video augmentation methods has been optimized.
3.Both English version and Chinese version have been updated.
4.The parts of model training and inferencing are added.

**Review by chg0901 — CHANGES_REQUESTED** [review]
could you please change the title of `Training` and `Inference` as  `Efficient Training` and `Efficient Inference` and also update the related table contents ?

Thanks for your consiferation

**Comment by chg0901** [comment]
@BestAnHongjun

**Comment by chg0901** [comment]
@BestAnHongjun  We are sorry to inform you that you need to update this PR as soon as possible and there are some conflicts, please try to recommit this PR.

**Pull request closed without merging**
