### PR TITLE
add [CVPR24] GenTron

### PR DESCRIPTION
**Pull request by ShoufaChen**
### Title
[Add/Update/Remove/Correct/Other] - Brief Description

### Summary
This pull request adds information about the **GenTron** paper to the README file. GenTron is video diffusion model for.

### CODE REVIEW

**Review by chg0901 — COMMENTED** [review]
I recommend keeping only the paper in the video generation section.

**Comment by ShoufaChen** [comment]
Hi @chg0901 

Thank you for your review. 

 I am sorry that I'm unclear on the rationale for limiting GenTron solely to the video section. Could you please clarify? It's evident that GenTron is a diffusion transformer work."

**Comment by chg0901** [comment]
> Hi @chg0901 
> 
> Thank you for your review. 
> 
>  I am sorry that I'm unclear on the rationale for limiting GenTron solely to the video section. Could you please clarify? It's evident that GenTron is a diffusion transformer work."
> 

In the video generation section, approximately half of the papers are related to transformer and diffusion-based models. It can be considered as a superset of the diffusion model paper list.

Thanks for your understanding to help us make this paper list efficiency.

**Comment by chg0901** [comment]
We understand that you want to let more people in the community know your work, So I would like to invite you to write a paper note to summarize your contributions and we will add a link to your notes if you could pr a markdown note file in ./notes folder.

**Review by chg0901 — APPROVED** [review]
Thanks for your understanding and your first pr.

**Comment by ShoufaChen** [comment]
Thank you for clarification and your awesome collection. I've updated it.

**Comment by chg0901** [comment]
> We understand that you want to let more people in the community know your work, So I would like to invite you to write a paper note to summarize your contributions and we will add a link to your notes if you could pr a markdown note file in ./notes folder.

@ShoufaChen if you have a new pr about the note I mentioned, please @me I will review and merge it as  soon as possible

**Comment by ShoufaChen** [comment]
@chg0901 

Thank you for your time. Let me first learn the note format 🚀

**Comment by chg0901** [comment]
> @chg0901 
> 
> Thank you for your time. Let me first learn the note format 🚀 

There is a note related to Latee paper in Chinese.

We would appreciate it if you could provide us both Chinese and English version.

**Pull request merged**
