### PR TITLE
[Bugs] about README.md and Readme_CN.md in codes and docs

### PR DESCRIPTION
**Pull request by ProAlize**
### Title
update README.md and Readme_CN.md in codes and docs

### Changes
Modify the links to Readme.md and Readme_CN.md

### Additional Comments
- Why is the README.md in the codes directory also Chinese?
-

### CODE REVIEW

**Review by chg0901 — APPROVED** [review]

**Comment by chg0901** [comment]
just find your question 'Why is the README.md in the codes directory also Chinese?'

could you please help us to translate it? It may be modified by contributors in mistake

**Comment by ProAlize** [comment]
Okay, my pleasure

**Comment by chg0901** [comment]
> Okay, my pleasure

thank you for reply, one of contributor is doing it, could you please help us to revise this code if you have time?
I will let you know if it is merged
#234

**Comment by chg0901** [comment]
By the way, I want to invite you to join our contributor group, could you please scan the QR code on the community and contact with me?

**Comment by ProAlize** [comment]
> By the way, I want to invite you to join our contributor group, could you please scan the QR code on the community and contact with me?
 Okay, it's a pleasure to join your group !

**Comment by ProAlize** [comment]
I have scanned the QR code to enter the group chat, how can I contact you?

**Comment by chg0901** [comment]
just show your github id or proAli, I will invite you

**Comment by ProAlize** [comment]
My WeChat id is the same as GitHub, and my avatar is also the same, and I am in the Diffusion video generation exchange group 6

**Pull request merged**
