### PR TITLE
Add Audio Related Resource Consistency

### PR DESCRIPTION
**Pull request by aplzem**
### Title
[Add/Update/Remove/Correct/Other] - Brief Description

### Summary
This pull request adds information about the NaturalSpeech 2/UniAudio paper to the README file. NaturalSpeech 2 is tts system with latent diffusion models .

### Changes
- Added a section in the README with links to the NaturalSpeech 2 paper, GitHub repository.
- Added a section in the README with links to the UniAudio paper, GitHub repository.
- Ensured that the links are functional and the information is up-to-date.

### Review Notes
- Checked both the Chinese and English READMEs have been updated at the same time
- Please review the added content for accuracy and formatting.
- Check that the links provided are correct and lead to the intended resources.
- **Please check if both the Chinese and English READMEs have been updated simultaneously.**

### Related Issues
- Closes #issue-number (if there's an associated issue)

### Additional Comments
- The addition of XXX to our README will provide valuable resources for users interested in efficient video generation.

### CODE REVIEW

**Review by chg0901 — CHANGES_REQUESTED** [review]
could you please also add `NaturalSpeech 1` into this list?

**Comment by aplzem** [comment]
> add `NaturalSpeech 1` into this list

Sure.I added NaturalSpeech 1 into this list,please check.

**Review by chg0901 — CHANGES_REQUESTED** [review]
How about moving NaturalSpeech in front of NaturalSpeech2

**Comment by aplzem** [comment]
> How about moving NaturalSpeech in front of NaturalSpeech2

Thank you for your suggestion. I have made the adjustment to place NaturalSpeech2 in front of NaturalSpeech, as per your request

**Review by chg0901 — APPROVED** [review]

**Pull request merged**
