### PR TITLE
[Update] - fix Issue #150 (file description in docs/README.md)

### LINKED ISSUE #150: [Add] - file description in docs/README.md
## **Detailed Description**

[Add] - file description in docs/README.md

Now it is empty.

### PR DESCRIPTION
**Pull request by BaiYu96**
### Summary

This PR is for fixing the Issue #150 which wanted to add a file description in docs/README.md

### Changes
- Added a file description in docs/README.md and the index to CONTRIBUTING.md

### Related Issues
- Closes #150

### CODE REVIEW

**Review by JunyaoHu — APPROVED** [review]

**Review by chg0901 — CHANGES_REQUESTED** [review]
Thank you for your PR. As a member, please follow the format of PR and Issue if it is not urgent.

The file link should be adopted such as `[简体中文](README.md) | [English](README_EN.md)` -->  `[简体中文](../README.md) | [English](../README_EN.md)`

**Review by JunyaoHu — CHANGES_REQUESTED** [review]
+1

**Comment by BaiYu96** [comment]
> Thank you for your PR. As a member, please follow the format of PR and Issue if it is not urgent.
> 
> The file link should be adopted such as `[简体中文](README.md) | [English](README_EN.md)` --> `[简体中文](../README.md) | [English](../README_EN.md)`

ok, I will update my PR description

**Review by chg0901 — APPROVED** [review]
thanks !

**Pull request merged**
