### PR TITLE
Update ReadMe file for Base Video Generation Models

### PR DESCRIPTION
**Pull request by AdamMayor2018**
### Title
Update ReadMe file for Base Video Generation Models

### Summary
This pull request adds information about the video diffusion related papers and  projects to the README file. 
-Stable Video Diffusion is for video generation
-Text2Video-Zero is for zero-shot video generation
-VideoCrafter2 is for high quality video generation

### Changes
- Added a section in the README with links to the video diffusion related papers, GitHub repository, and project website.
- Ensured that the links are functional and the information is up-to-date.

### Review Notes
- Please review the added content for accuracy and formatting.
- Check that the links provided are correct and lead to the intended resources.
- **Please check if both the Chinese and English READMEs have been updated simultaneously.**

### Related Issues
- Closes #issue-number (if there's an associated issue)

### Additional Comments
- The addition of XXX to our README will provide valuable resources for users interested in efficient video generation.

### CODE REVIEW

**Review by chg0901 — CHANGES_REQUESTED** [review]
Please check if your updated papers already are in the list.

such as `Video Diffusion Models`

For Paper Names,  please follow the style with conference or journal short name

**Comment by AdamMayor2018** [comment]
Delete a duplicate paper Video Diffusion Models.

**Review by chg0901 — CHANGES_REQUESTED** [review]
I just found that Stable Video Diffusion paper also exists. Could you please help us delete it and modify the numbers. We agree that SVD could be a baseline model.

However, I am not familiar with the other two papers.

By the way, if you add the paper xxx2, you can also add the baseline xxxx to the related section(not in the baseline section)

Thanks for your understanding and consideration.

**Comment by AdamMayor2018** [comment]
remove a duplicate paper SVD
add 1 new paper videocrafter1

**Review by chg0901 — APPROVED** [review]

**Pull request merged**
